import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import axios from "axios";
import { Separator } from "@/components/ui/separator";
import Footer from "@/components/Footer";
// import Providers from "@/context/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // fetch /api/posts
  try {
    // todo change it when deployment
    const res = await axios.get("http://localhost:3000/api/posts");
  } catch (error) {}

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Providers> */}
        <Navbar />
        {children}
        {/* </Providers> */}
        <Footer />
      </body>
    </html>
  );
}
